version: "3.7"
services:
  app:
    build: .
    ports:
      - 5174:5174
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: ["sh", "-c"]
    command: ["npm run dev"]
